### ISSUE TITLE
atom-ternjs disables atom api code completion

### ISSUE THREAD

**Issue by peduxe** [tststs/atom-ternjs#104]
When atom-ternjs is enabled it disables atom API autocomplete (writing packages).

https://github.com/atom/autocomplete-atom-api

**Comment by tststs** [comment]
the package excludes all lower priority providers.
good point! in the next release i will provide an option to disable this behaviour so you can manually disable it.

**Comment by peduxe** [comment]
Great to hear.

**Comment by jhicken** [comment]
I suspect this is why https://atom.io/packages/autocomplete-paths does not work with atom-ternjs enabled. Can anybody confirm that?
