### ISSUE TITLE
ES6 class does not do support Find Reference and Find Definition

### ISSUE THREAD

**Issue by jannavarro** [tststs/atom-ternjs#105]
I have an ES6 class and which is being accessed in different files. The Find Reference and Find Definition does not do anything when I do it on a method in the class.

**Comment by tststs** [comment]
tern does not support es6 at the moment. have a look @ https://github.com/marijnh/tern to get updates about es6. it seems, that development has recently started.

**Comment by jannavarro** [comment]
Thanks.
