### ISSUE TITLE
Unknown identifier 'x' shown on end curly brace

### ISSUE THREAD

**Issue by jannavarro** [tststs/atom-ternjs#106]
atom-ternjs uses linter. I found an issue so I logged [this](https://github.com/atom-community/linter/issues/774) in linter but they closed it and said the bug belong to the linter provider. Anybody knows if this should be fixed by atom-ternjs or some other plugin?

**Comment by tststs** [comment]
You have some example code to reproduce the issue?

**Comment by jannavarro** [comment]
A few reload of Atom made the warning disappear.
