### ISSUE TITLE
Uncaught TypeError: Cannot read property 'provide' of undefined

### ISSUE THREAD

**Issue by filipesilva** [tststs/atom-ternjs#11]
Hi there, was trying to install this package and this happened. I have node installed, and it is on user PATH. It does install though, but nothing comes up in the command pane.

If I restart atom, options come up in the command page but using the one that creates the project file outputs the same error.

1. Try to install package

**Atom Version**: 0.176.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [atom-ternjs](https://github.com/tststs/atom-ternjs) package, v0.4.8

### Stack Trace

Uncaught TypeError: Cannot read property 'provide' of undefined

```
At /c:/Users/filipe.silva.3VTS/.atom/packages/atom-ternjs/lib/atom-ternjs.coffee:98

TypeError: Cannot read property 'provide' of undefined
  at AtomTernInitializer.activatePackage (c:\Users\filipe.silva.3VTS\.atom\packages\atom-ternjs\lib\atom-ternjs.coffee:73:45)
  at AtomTernInitializer.init (c:\Users\filipe.silva.3VTS\.atom\packages\atom-ternjs\lib\atom-ternjs.coffee:76:6)
  at c:\Users\filipe.silva.3VTS\.atom\packages\atom-ternjs\lib\atom-ternjs.coffee:104:10
  at stdout (c:\Users\filipe.silva.3VTS\.atom\packages\atom-ternjs\lib\atom-ternjs-server.coffee:16:7)
  at Socket.<anonymous> (c:\Users\filipe.silva.3VTS\AppData\Local\atom\app-0.176.0\resources\app\src\buffered-process.js:137:13)
  at Socket.emit (events.js:107:17)
  at readableAddChunk (_stream_readable.js:161:16)
  at Socket.Readable.push (_stream_readable.js:125:10)
  at Pipe.onread (net.js:522:20)

```

### Commands

```
     -7:19.2 symbols-view:toggle-file-symbols (atom-text-editor.editor)
     -7:00.8 pane:reopen-closed-item (atom-text-editor.editor)
     -4:33.9 settings-view:open (atom-text-editor.editor)
     -4:23.7 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-ctags",
      "Tern",
      "linter-phpcs",
      "remember-session",
      "linter-jscs",
      "sublime-tabs"
    ],
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
atom-ternjs, v0.4.8
autocomplete-plus, v2.0.10
autocomplete-snippets, v1.0.0
color-picker, v1.4.4
file-icons, v1.4.8
git-log, v0.2.0
linter, v0.11.1
linter-jshint, v0.1.0
minimap, v4.0.1
Sublime-Style-Column-Selection, v1.2.3

# Dev
No dev packages
```

/cc @atom/core

**Comment by tststs** [comment]
Pls update to atom 0.177 and try again

**Comment by filipesilva** [comment]
It doesn't seem to be available on the windows install right now, but I will try again later and tell you the result.

**Comment by tststs** [comment]
Ah, haven't thought about that. :/
You may change this file in order to make it work, if 0.177 is not released for a while.
It's located at .atom/packages/atom-ternjs/lib/...
https://github.com/tststs/atom-ternjs/commit/63842c9105e2373ee5be4502eaa30095eb8bb6c2

Thx for reporting!

**Comment by filipesilva** [comment]
It usually takes some 12h or so for the windows auto updater to pick up the new ones, so it's not a big problem!

**Comment by tststs** [comment]
does it work with the latest version?

**Comment by filipesilva** [comment]
Latest version has a problem with Windows, unfortunately! I cannot install it, but there is a fix incoming. 
https://github.com/atom/atom/issues/5109

I'm still keeping an eye on this one though, I've waited very very long for good tern support on atom!

**Comment by filipesilva** [comment]
I tried it on my personal machine, and it works great! I'm so looking forward to this :D
