### ISSUE TITLE
I'm getting the following error whenever I create an object and I've only typed the property name but not yet the colon

### ISSUE THREAD

**Issue by RobertWHurst** [tststs/atom-ternjs#113]
Whenever I create an object I get the following error. It happens while I'm writing the first property name before I add the colon. Perhaps it has something to do with when the object is interpreted as a code block instead of an object?

![screen shot 2015-08-14 at 11 15 40 am](https://cloud.githubusercontent.com/assets/178857/9280821/d98dcb60-4275-11e5-906d-541cf7e531cb.png)

> TypeError: Cannot read property 'CallExpression' of undefined at findTypeFromContext.NewExpression (/Users/rhurst/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:1588:18) at Object.exports.typeFromContext (/Users/rhurst/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:1623:24) at Object.findCompletions [as run] (/Users/rhurst/.atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:684:23) at run (/Users/rhurst/.atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:218:30) at Object.exports.withContext (/Users/rhurst/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:774:18) at /Users/rhurst/.atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:225:13 at analyzeAll (/Users/rhurst/.atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:339:15) at doRequest (/Users/rhurst/.atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:209:5) at Object.signal.mixin.request (/Users/rhurst/.atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:149:7) at respond (/Users/rhurst/.atom/packages/atom-ternjs/node_modules/tern/bin/tern:224:10)

**Comment by tststs** [comment]
Be sure to update to the latest version of tern.

```
cd ~/.atom/packages/atom-ternjs
npm update
```

If the issue still exists after the update, please open a issue @ [marijnh/tern](https://github.com/marijnh/tern) and reference this issue.

greeting,
tststs

**Comment by tststs** [comment]
Does the issue still exists?
