### ISSUE TITLE
TypeError: Cannot read property 'CallExpression' of undefined at findTypeFromContext.NewExpression

### ISSUE THREAD

**Issue by rbecheras** [tststs/atom-ternjs#115]
Hi guys!

Today I get this error into a 'alert styled' flash message box in the editor window's top right corner:

>    TypeError: Cannot read property 'CallExpression' of undefined at findTypeFromContext.NewExpression (/home/poremil/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:1588:18) at Object.exports.typeFromContext (/home/poremil/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:1623:24) at Object.findCompletions [as run] (/home/poremil/.atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:684:23) at run (/home/poremil/.atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:218:30) at Object.exports.withContext (/home/poremil/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:774:18) at /home/poremil/.atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:225:13 at analyzeAll (/home/poremil/.atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:339:15) at doRequest (/home/poremil/.atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:209:5) at Object.signal.mixin.request (/home/poremil/.atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:149:7) at respond (/home/poremil/.atom/packages/atom-ternjs/node_modules/tern/bin/tern:224:10)

However, a didn't notice any specific bug in my workflow. That said, I would want to understand what happend.

I also posted this in a stackoverflow question: https://stackoverflow.com/questions/32023924/error-in-atom-package-ternjs

**Comment by tststs** [comment]
@marijnh

**Comment by rbecheras** [comment]
Here is [a response to my question on Stackoverflow](http://stackoverflow.com/a/32025881/3197383).
I past it here if it can help you, maintainers, to track the bug.


 «
==


Yes, this does look like a bug.
Here is a simplified extract from the breaking code:

    var findTypeFromContext = {
      NewExpression: function() { return this.CallExpression() }
      ,CallExpression: function() { console.log('calling expression'); }
    }
    var finder = findTypeFromContext['NewExpression'];
    finder();

This breaks because of the *this* keyword.

 1. The `var finder = findTypeFromContext['NewExpression'];` assignment takes NewExpression method "out" (detaching from the parent object). 
 2. By this assignment the *this* keyword now points to the current parent object - where CallExpression does not exists.

My quick-fix would be to immediately call the function on the object so *this* is still pointing at the right place:

    var findTypeFromContext = {
      NewExpression: function() { this.CallExpression() }
      ,CallExpression: function() { console.log('calling expression'); }
    }
    findTypeFromContext['NewExpression']();

»
==

**Comment by ShaharHD** [comment]
Try the following:
```
cd ~/.atom/packages/atom-ternjs
npm update
```

This will make atom-ternjs to pull again the latest version of tern from github into node_modules. (the error should have been fixed in the last commit)

**Comment by rbecheras** [comment]
Thank you, its done!

**Comment by rbecheras** [comment]
The issue should be closed now

**Comment by tststs** [comment]
Fixed with latest version of tern.
atom-ternjs 0.7.2 will automatically update node_modules.

**Comment by rbecheras** [comment]
Thanks!
