### ISSUE TITLE
new imports cause crashes

### ISSUE THREAD

**Issue by futuraprime** [tststs/atom-ternjs#119]
Whenever I start typing an `import` statement (using es6 import syntax), Tern crashes. Once I finish writing the statement, Tern reads the file just fine.

It seems to crash as soon as I type `import `, and appears to crash when editing any file with an incomplete `import`. I can go on restarting Tern after I finish the import, but this is pretty tedious.

**Comment by tststs** [comment]
Tern has no real ES6 support at the moment. Please subscribe marijnh/tern to receive updates about this.
You may also create a issue @ marijnh/tern and reference this issue.

greeting,
tststs

**Comment by tststs** [comment]
Should be fixed with 0.7.4.
