### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by ginus** [tststs/atom-ternjs#12]
atom.services is no longer available. To register service providers and
consumers, use the `providedServices` and `consumedServices` fields in
your package's package.json.
```
Atom.Object.defineProperty.get (C:\Users\Administrator\AppData\Local\atom\app-0.177.0\resources\app\src\atom.js:64:11)
AtomTernInitializer.activatePackage (C:\Users\Administrator\.atom\packages\atom-ternjs\lib\atom-ternjs.coffee:65:25)
```

**Comment by tststs** [comment]
Did you update to the latest version?
atom.services is no longer being used.

Thx
tststs

**Comment by tststs** [comment]
does it work with the latest version?

**Comment by ginus** [comment]
with atom 177 and your package 0.4.9 it works! thanks good job!
