### ISSUE TITLE
It did not suggest the method I need

### ISSUE THREAD

**Issue by unluisco** [tststs/atom-ternjs#123]
I was looking for '.innerText' but is not on the list, I have the 4 libraries activated.

![intro js - users unluisco dropbox unluisco pruebas - atom 2015-09-02 19-24-58](https://cloud.githubusercontent.com/assets/6332263/9647946/6a1a1b48-51a8-11e5-997b-fd152a884bb5.png)

How I can get the suggestions that are not on the list?

**Comment by tststs** [comment]
Please use ```textContent```.
``ìnnerText``` is (i think) IE only and not part of ecma.
