### ISSUE TITLE
crash when using es6 import *

### ISSUE THREAD

**Issue by arisAlexis** [tststs/atom-ternjs#127]
the following crash happens after writing "import * from" **which is a syntax mistake**

I am using eslint and my .tern file is:

{
  "libs": [
    "browser",
    "ecma5",
    "ecma6"
  ],
  "loadEagerly": [
    "services/**/*.js"
  ],
  "plugins":{
    "doc_comment": {
      "fullDocs": true
    }
  }
}

atom version is latest 1.0.1

error
undefined Unexpected token
at line 13 col 1 in services/mailService.js
File 1Project 11 Issueservices/mailService.js11:10
LFUTF-8JavaScriptmaster2+44
atom-ternjs
/home/aris/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:1045 return scope.defProp(nameNode.name, nameNode); ^ TypeError: Cannot read property 'name' of undefined at addVar (/home/aris/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:1045:34) at Object.walk.make.ImportDeclaration (/home/aris/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:1149:9) at c (/home/aris/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:68:35) at Object.skipThrough (/home/aris/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:168:3) at c (/home/aris/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:68:35) at Object.base.Program.base.BlockStatement [as Program] (/home/aris/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:179:5) at c (/home/aris/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:68:35) at Object.recursive (/home/aris/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:69:5) at Object.exports.analyze (/home/aris/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:1709:10) at /home/aris/.atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:267:13

**Comment by tststs** [comment]
Feel free to post a issue to [marijnh/tern](https://github.com/marijnh/tern).
