### ISSUE TITLE
function autocomplete conflicts with built in function snippet

### ISSUE THREAD

**Issue by keirlawson** [tststs/atom-ternjs#129]
To reproduce:

type `fun`, press tab, type function name, press tab

expected:

cursor moves to function argument placeholder

actual:

additional (redundant) set of braces are added with additional argument

ie 
```function foobarbaz(argument: ?)(argument) {
  // body...
}```

**Comment by tststs** [comment]
Could you please provide used plugins, code examples and your configuration file?
Haven't managed to reproduce this.

Greetings,
tststs

**Comment by keirlawson** [comment]
Used plugins:

.../Code/Angular/acidtwo    master    apm list --depth=0                                                     ✓ 
Built-in Atom packages (90)
├── about@1.1.0
├── archive-view@0.60.0
├── atom-dark-syntax@0.27.0
├── atom-dark-ui@0.51.0
├── atom-light-syntax@0.28.0
├── atom-light-ui@0.43.0
├── autocomplete-atom-api@0.9.2
├── autocomplete-css@0.11.0
├── autocomplete-html@0.7.2
├── autocomplete-plus@2.19.1
├── autocomplete-snippets@1.7.1
├── autoflow@0.25.0
├── autosave@0.22.0
├── background-tips@0.26.0
├── base16-tomorrow-dark-theme@0.27.0
├── base16-tomorrow-light-theme@0.9.0
├── bookmarks@0.37.0
├── bracket-matcher@0.76.0
├── command-palette@0.36.0
├── deprecation-cop@0.54.0
├── dev-live-reload@0.46.0
├── encoding-selector@0.21.0
├── exception-reporting@0.37.0
├── find-and-replace@0.181.0
├── fuzzy-finder@0.88.0
├── git-diff@0.56.0
├── go-to-line@0.30.0
├── grammar-selector@0.47.0
├── image-view@0.54.0
├── incompatible-packages@0.25.0
├── keybinding-resolver@0.33.0
├── language-c@0.48.0
├── language-clojure@0.16.0
├── language-coffee-script@0.41.0
├── language-csharp@0.10.0
├── language-css@0.34.0
├── language-gfm@0.81.0
├── language-git@0.10.0
├── language-go@0.37.0
├── language-html@0.41.2
├── language-hyperlink@0.14.0
├── language-java@0.16.0
├── language-javascript@0.94.0
├── language-json@0.16.0
├── language-less@0.28.2
├── language-make@0.17.0
├── language-mustache@0.12.0
├── language-objective-c@0.15.0
├── language-perl@0.29.0
├── language-php@0.30.0
├── language-property-list@0.8.0
├── language-python@0.40.0
├── language-ruby@0.58.0
├── language-ruby-on-rails@0.22.0
├── language-sass@0.41.0
├── language-shellscript@0.17.0
├── language-source@0.9.0
├── language-sql@0.17.0
├── language-text@0.7.0
├── language-todo@0.27.0
├── language-toml@0.16.0
├── language-xml@0.32.0
├── language-yaml@0.24.0
├── line-ending-selector@0.0.5
├── link@0.30.0
├── markdown-preview@0.150.0
├── metrics@0.51.0
├── notifications@0.59.0
├── one-dark-syntax@1.1.0
├── one-dark-ui@1.0.4
├── one-light-syntax@1.1.0
├── one-light-ui@1.0.4
├── open-on-github@0.38.0
├── package-generator@0.40.0
├── release-notes@0.53.0
├── settings-view@0.216.0
├── snippets@0.99.0
├── solarized-dark-syntax@0.38.1
├── solarized-light-syntax@0.22.1
├── spell-check@0.59.0
├── status-bar@0.79.0
├── styleguide@0.44.0
├── symbols-view@0.104.0
├── tabs@0.84.0
├── timecop@0.31.0
├── tree-view@0.187.0
├── update-package-dependencies@0.10.0
├── welcome@0.30.0
├── whitespace@0.31.0
└── wrap-guide@0.36.0

/home/keir/.atom/packages (21)
├── Stylus@1.2.1
├── angularjs@0.3.0
├── atom-ternjs@0.7.2
├── autoclose-html@0.19.0
├── autocomplete-paths@1.0.2
├── autocomplete-php@0.3.7
├── docblockr@0.7.3
├── editorconfig@1.2.0
├── git-projects@1.15.0
├── highlight-line@0.11.0
├── highlight-selected@0.10.1
├── language-gradle@0.0.3
├── language-groovy@0.4.0
├── language-jade@0.6.2
├── language-scala@1.1.3
├── linter@1.5.1
├── linter-eslint@3.0.2
├── linter-jshint@1.2.0
├── linter-php@1.0.3
├── minimap@4.13.3
└── react@0.12.9

**Comment by keirlawson** [comment]
Config:

"*":
  "exception-reporting":
    userId: "dc9bb00d-8d6f-9125-6974-496ce3533beb"
  welcome:
    showOnStartup: false
  metrics:
    userId: "aabfbb00b3cd5cdf5fa0e22ea2a648dbc3e8395a"
  core:
    disabledPackages: [
      "language-objective-c"
      "deprecation-cop"
      "language-c"
      "language-clojure"
      "language-coffee-script"
      "language-go"
      "language-mustache"
      "language-perl"
      "language-python"
      "language-ruby"
      "language-ruby-on-rails"
      "language-toml"
      "atom-lint"
      "atom-typescript"
    ]
    themes: [
      "one-light-ui"
      "one-light-syntax"
    ]
    audioBeep: false
  "highlight-line":
    enableBackgroundColor: false
    enableSelectionBorder: true
  "tree-view":
    hideVcsIgnoredFiles: true
  editor:
    invisibles: {}
    fontSize: 16
  "autoclose-html": {}
  linter:
    lintOnChangeInterval: 0
    lintOnChange: false
    showErrorPanel: false
  "linter-jshint":
    disableWhenNoJshintrcFileInPath: true
  "autocomplete-plus": {}
  "linter-eslint":
    disableWhenNoEslintrcFileInPath: true
  "merge-conflicts": {}
  "git-projects":
    rootPath: "/home/keir/Code/Angular"
    maxDepth: 2
  "atom-ternjs": {}
  docblockr:
    return_tag: "@returns"
  react: {}

**Comment by keirlawson** [comment]
![anim](https://cloud.githubusercontent.com/assets/49213/10361219/7a9e2fba-6d9e-11e5-82d3-cc04231e4288.gif)

**Comment by jordanbtucker** [comment]
This isn't really a conflict with the built-in `fun` snippet per se. It's an issue with any function that already exists. Find or write any declared function, that is in the form `function name()` not `var name = function()` and replace `name` with something else. You'll see this:

![image](https://cloud.githubusercontent.com/assets/468153/10522072/0ee7f924-7328-11e5-8f3f-402698b31417.png)

If you press tab with that `test(argument: ?)` suggestion selected, it will insert a new parameter list directly before your existing one. This may be an issue with [tern] rather than atom-ternjs.

[tern]: https://github.com/marijnh/tern
