### ISSUE TITLE
Unsaved Files Cause "Bad Request" AJAX Errors

### ISSUE THREAD

**Issue by MethodGrab** [tststs/atom-ternjs#132]
Atom 1.0.11
atom-ternjs 0.7.2

If you open a new file but don't save it, `atom-ternjs` will spam the console with 400 (Bad Request) AJAX errors every time you type:

![image](https://cloud.githubusercontent.com/assets/2421069/9875107/6c0daf3c-5ba3-11e5-9c54-de900e33b80e.png)

The response from the server is:
```
.files[n].name must be a string
```

I think it would be preferable to catch these errors and ignore them or not run the plugin against unsaved files.

**Comment by tststs** [comment]
Haven't managed to reproduce this yet.
Fell free to post a pull request that handles the case.
Else, you may give me more detailed directions to reproduce the error.

Greetings,
tststs

**Comment by MethodGrab** [comment]
I'm using 0.8.3 now and I can't reproduce it anymore so I'll close this.
