### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by kai0** [tststs/atom-ternjs#134]
Specs:
- OSX Yosemite 10.10.5.
- Atom 1.0.15.
- Latest version of atom-ternjs.

Symptoms:
With the following autocomplete options enabled:
```
{
  "libs": [
    "browser",
    "ecma5",
    "ecma6"
  ],
  "plugins": {
    "node": {}
  }
}
```

after a while, CPU usage soars to ~90%. It goes down to normal levels after restarting the server. Rinse and repeat.

**Comment by jakubholynet** [comment]
I have also huge performance problems with tern (same setup as you but now special tern config). Whenever I start Atom / restart tern, CPU goes to 100% and stays there for quite a few minutes :(

**Comment by alferpal** [comment]
I'm seeing the same issue with this config:

```
{
  "ecmaVersion": 6,
  "libs": [],
  "plugins": {
    "complete_strings": {},
    "node": {},
    "doc_comment": {
      "fullDocs": true
    }
  }
}
```

**Comment by markrendle** [comment]
+1

```json
{
  "ecmaVersion": 6,
  "libs": [],
  "plugins": {
    "node": {"load":true}
  }
}
```

`Linux #### 4.1.12-1-MANJARO #1 SMP PREEMPT Tue Oct 27 22:11:47 UTC 2015 x86_64 GNU/Linux`

`atom 1.1.0`

**Comment by markrendle** [comment]
Bit of research, I suspect this is related to trying to load all of `node_modules`. I've set the `dependencyBudget` field in `.tern-project` to `5000` (the default is `20000`), seems to be OK for now but I'll keep an eye on it...

**Comment by tststs** [comment]
closing this in favor of #193
