### ISSUE TITLE
Error with ES6 & Promises

### ISSUE THREAD

**Issue by sigxcpu76** [tststs/atom-ternjs#136]
It happens when the cursor is over the ```function``` keyword in ```...then(function(...```

TypeError: self.hasProp is not a function at /Users/sigxcpu/.atom/packages/atom-ternjs/node_modules/tern/lib/def.js:633:37 at fn.computeRet (/Users/sigxcpu/.atom/packages/atom-ternjs/node_modules/tern/lib/def.js:257:26) at fn.computeRet (/Users/sigxcpu/.atom/packages/atom-ternjs/node_modules/tern/lib/def.js:257:26) at fn.computeRet (/Users/sigxcpu/.atom/packages/atom-ternjs/node_modules/tern/lib/def.js:257:26) at computeReturnType (/Users/sigxcpu/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:1826:19) at typeFinder.CallExpression (/Users/sigxcpu/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:1883:14) at findType (/Users/sigxcpu/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:1917:21) at typeFinder.MemberExpression (/Users/sigxcpu/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:1886:41) at findType (/Users/sigxcpu/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:1917:21) at computeReturnType (/Users/sigxcpu/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:1817:14)

I'll forward this to tern as I've observed later that it is its issue, sorry.

**Comment by tststs** [comment]
Should be fixed with 0.7.4.
