### ISSUE TITLE
can't install plugin

### ISSUE THREAD

**Issue by agileago** [tststs/atom-ternjs#137]
```
Failed to install atom-ternjs because Git was not found.

The atom-ternjs package has module dependencies that cannot be installed without Git.

You need to install Git and add it to your path environment variable in order to install this package.

Run apm -v after installing Git to see what version has been detected.
```

but i have installed git yet  . and i run apm -v will find 
![image](https://cloud.githubusercontent.com/assets/11799110/10117073/92e35d82-647c-11e5-8b7d-0f77f655a747.png)

and in my zsh 
![image](https://cloud.githubusercontent.com/assets/11799110/10117077/b724c532-647c-11e5-91cc-df147799bf24.png)

**Comment by agileago** [comment]
![image](https://cloud.githubusercontent.com/assets/11799110/10117080/e02e301c-647c-11e5-8a39-b7d0674bbced.png)

**Comment by agileago** [comment]
when i use `apm install atom-ternjs`. i can install it. but it seems that the plugin's functions is not full.
it is so hard to use

**Comment by tststs** [comment]
You may report this issue to atom. Maybe there are some dependencies located in package.json, for which this configuration doesn't work. Keep me updated, i will try to find the time to solve the issue if it is related to ```atom-ternjs```.

Greetings,
tststs
