### ISSUE TITLE
Can't Find phaser plugin OSX

### ISSUE THREAD

**Issue by echorebel** [tststs/atom-ternjs#139]
Running on OSX and as described here https://github.com/angelozerr/tern-phaser/wiki/UseTernPhaserWithAtom
i installed tern-phaser via npm install -g tern-phaser.
It was installed to /usr/local/lib/node_modules/tern-phaser.
Atom still can't find it.
How is the lookup solved? Can i fix the path?

**Comment by tststs** [comment]
As a workaround: 

```$ cd [USER_PATH]/.atom/packages/atom-ternjs```

then simple:

```$ npm install tern-phaser```

Restart atom and you should be good to go.
These steps needs to be done everytime atom-ternjs is updated.

You may or should open a issue @ [tern](https://github.com/marijnh/tern) to search for plugins in the global space or ask @angelozerr how he managed to make it work. I think this is a common problem with ```atom-ternjs``` and i would love to see some feedback on that. I simple don't find time to manage it by myself.

Greetings,
tststs

**Comment by echorebel** [comment]
ok thx 4 the workaround.
if i find time i will check the tern doc http://ternjs.net/doc/manual.html#plugin_third_party
