### ISSUE TITLE
Process out of Memory

### ISSUE THREAD

**Issue by limianwang** [tststs/atom-ternjs#140]
Since the latest update (0.8.2), I've been experiencing some errors regarding process out of memory.

```
├── atom-ternjs@0.8.2
```

```
atom-ternjs
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
tern exited with code: null.
Restart the server via Packages -> Atom Ternjs -> Restart server
```

Any one have a clue?

**Comment by domrein** [comment]
I've been seeing this too. I'm working on a mid sized project with a dozen or so node modules. Adding node_modules to "dontLoad" seems to make the error occur a lot less often.

**Comment by RobertWHurst** [comment]
I've also been having this issue quite a lot. Thinking about switching back to atom's builtin auto complete.

**Comment by tststs** [comment]
Then you should just switch back to the build in auto complete if you are not happy. It's not like you are paying for this package or contributing or anything?! These kind of comments are not welcome here and are not helpful in any way.

Thank you.

**Comment by ricardograca** [comment]
It seems to crash V8. I noticed an `atom` process that was consuming 1.4GB of ram when this happened. I got a stack trace but I don't think it's helpful since it just points to `/usr/share/atom/libnode.so`.

**Comment by RobertWHurst** [comment]
@tststs Very professional. I'm not slandering your work by explaining the severity of a bug. This is an issue tracker is it not?

**Comment by philiiiiiipp** [comment]
I also see the atom helper going up to 1.4GB when atom/ternjs is running. After I disable it, the memory drops significantly by at least 1GB to below 400MB. 
My ternjs file is:
```
{
  "ecmaVersion": 6,
  "libs": [
    "browser"
  ],
  "dontLoad": [
    "dist/**",
    "node_modules"
  ],
  "loadEagerly": [
    "src/**/*.js"
  ],
  "plugins": {
    "complete_strings": {},
    "node": {},
    "modules": {},
    "es_modules": {},
    "doc_comment": {
      "fullDocs": true
    }
  }
}
```

my source folder contains 15 files at the moment with none of them containing more than 30 lines of code (No minification or long lines).

I fiddled around a bit to pinpoint what exactly does cause the increase in memory, but it was quite hard to find a cause other than "After using it for some time it's at 1.4GB".

It also felt as if opening files within the dist folder which it should not load and are huge caused the memory consumption to dramatically increase. But this might also just be another plugin/atom using the memory.

If there is any more I can check for I will happily do so.
