### ISSUE TITLE
atom-ternjs switches port it sends requests to after some time

### ISSUE THREAD

**Issue by senordev** [tststs/atom-ternjs#142]
For some reason the plugin decides to switch the port that it polls after some time. Tern is still running and accepting connections on the initial port. I have verified by making manual requests using cURL.
Initial port and successful request:
<img width="859" alt="screen shot 2015-10-11 at 1 28 18 pm" src="https://cloud.githubusercontent.com/assets/1820187/10418281/830e76fc-701c-11e5-914b-0a13dadc2300.png">

New port and unsuccessful request:
<img width="859" alt="screen shot 2015-10-11 at 1 28 15 pm" src="https://cloud.githubusercontent.com/assets/1820187/10418283/91caf242-701c-11e5-8439-bbfa152fdb69.png">

I'm able to reproduce this issue with only one specific file I'm editing, a nodejs file.

The problem disappears when commenting out or removing the require statements at the top of the file.

**Comment by vhKarel** [comment]
I have the same issue. It happens while working in any file. To get TernJS to work again I have to restart Atom or the TernJS server. 
![3f141234-7195-11e5-90d7-4902f6b57195](https://cloud.githubusercontent.com/assets/9048726/10482361/ed4bbe78-7277-11e5-8a9b-49ed37465a99.jpg)
![3f13b5dc-7195-11e5-8fd7-2232b40b33c9](https://cloud.githubusercontent.com/assets/9048726/10482364/f0d4a7bc-7277-11e5-90ed-a0050effadfc.jpg)

**Comment by senordev** [comment]
This seems like it's due to the lint plugin for tern. When disabling that plugin, I'm unable to reproduce this issue.

**Comment by tststs** [comment]
@angelozerr

**Comment by angelozerr** [comment]
> This seems like it's due to the lint plugin for tern.

Have you a stacktrace error where tern lint crashes please?

**Comment by tststs** [comment]
Does the issue still exists?
Tested everything and it seems to be fixed.

**Comment by karelvh** [comment]
Yup it seems solved. Haven't encountered the issue in a few weeks.

**Comment by tststs** [comment]
:+1:
