### ISSUE TITLE
Keybinding for tern:references conflicst with builtin symbols-view:toggle-project-symbols

### ISSUE THREAD

**Issue by forivall** [tststs/atom-ternjs#143]
i would change it to ctrl-shift-e, mainly becase i already use alt-shift-r

**Comment by tststs** [comment]
On mac: ctrl-shift-E is the shortcut for editor:select-to-end-of-line (core).
Keybinding hell as always.

**Comment by forivall** [comment]
can it be cmd-shift-e on macs?
