### ISSUE TITLE
unsupported URL error when updating from 0.8.2 -> 0.8.4

### ISSUE THREAD

**Issue by StickyCube** [tststs/atom-ternjs#153]
I assume this is something to do with my version of npm/node as noone else has reported it.
I've tried reinstalling/updating npm and node but it doesnt seem to make a difference.
Has anyone else run into this?

npm ERR! Unsupported URL Type: github:marijnh/tern
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-115926-30644-35qcff/npm-debug.log

Cheers

**Comment by jordanbtucker** [comment]
Can you run `apm -v` and list the results? Thanks.

**Comment by StickyCube** [comment]
apm  1.0.1
npm  2.5.1
node 0.10.35
python 2.7.6
git 1.9.1

**Comment by jordanbtucker** [comment]
It looks like apm 1.0.1 uses npm 2.5.1, which might not support the `github:` style of URLs. Try upgrading apm and/or atom and see if that resolves the issue.

**Comment by StickyCube** [comment]
I reinstalled atom by building from source. and it now works.
Thanks for the help
