### ISSUE TITLE
Ctrl-Shift-R conflicts with other symbol packages (ctags).

### ISSUE THREAD

**Issue by ferdynice** [tststs/atom-ternjs#154]
Ctrl-Shift-R conflicts with other symbol packages (ctags). I'm not saying it should use something different, but is there a simple way to fix this?

I was guessing something to only binding it when in .js files, but not sure if this is currently possible to configure.

**Comment by jordanbtucker** [comment]
Put this in your keymap (File > Open Your Keymap):

```cson
# Stop atom-ternjs from hijacking ctrl-shift-r
'atom-text-editor':
  'ctrl-shift-r': 'unset!'
```

If you want to use atom-ternjs references in your JavaScript files, then add this too:

```cson
# Open atom-ternjs references in JavaScript files
'atom-text-editor[data-grammar="source js"]':
  'ctrl-shift-r': 'tern:references'
```

**Comment by ferdynice** [comment]
Thanks! Exactly what I was looking for.
