### ISSUE TITLE
Crash when used with ES6 syntax

### ISSUE THREAD

**Issue by Cortys** [tststs/atom-ternjs#155]
The tern server crashes as soon as I move inside the parentheses of a function call or declaration to inspect the inferred parameter types.

**Stack trace:**
```
tern/lib/infer.js:1531 self.propagate(new HasMethodCall(pName, args, node.arguments, out));
                                     ^ TypeError: self.propagate is not a function
  at tern/lib/infer.js:1531:14
  at tern/lib/infer.js:1359:7
  at infer (tern/lib/infer.js:1607:22)
  at Object.exports.inferWrapper.walk.make.Expression (tern/lib/infer.js:1616:7)
  at c (tern/node_modules/acorn/dist/walk.js:68:35)
  at Object.base.ExpressionStatement.base.ParenthesizedExpression (tern/node_modules/acorn/dist/walk.js:186:10) 
  at c (tern/node_modules/acorn/dist/walk.js:68:35)
  at Object.exports.inferWrapper.walk.make.Statement (tern/lib/infer.js:1628:7)
  at c (tern/node_modules/acorn/dist/walk.js:68:35)
  at Object.base.Program.base.BlockStatement (tern/node_modules/acorn/dist/walk.js:180:5)
```

**`.tern-project` file:**
```json
{
	"ecmaVersion": 6,
	"libs": [],
	"loadEagerly": [
		"src/**/*.js"
	],
	"plugins": {
		"doc_comment": {
			"fullDocs": true
		},
		"node": {},
		"complete_strings": {}
	}
}
```

This only happens in larger projects and apparently only when using ES6 syntax. I was not able to quickly put together a small staged example where this happens but I can reliably reproduce this issue when working with [this](/runnr/runnr) repository. The issue is reproducible at pretty much every js file in there.

I'm using Atom 1.1.0 on OS X 10.11.1 with the latest version of this extension (0.8.4 as of writing) and since tern is included via GitHub I made sure that the currently latest commit https://github.com/ternjs/tern/commit/5e9b6728219ab443a7dd85222f6e06458bb1b5f1 is installed. Idk if it matters but the globally installed node version is 5.0.0 with npm 3.3.6.

It looks like this is a problem with tern itself but since I'm not familiar at all with the codebase I thought it was best to report this issue in a top-down order.

If you need any further information please let me know.

**Comment by jordanbtucker** [comment]
I agree that this looks like a Tern issue. Can you please report it there, too? Thanks.

**Comment by Cortys** [comment]
See https://github.com/ternjs/tern/issues/675. Looks like the issue somehow disappeared after restarting Atom yesterday, which I did before multiple times without success.

I'll report again if the problem should reappear.
