### ISSUE TITLE
tern exited with code: null.

### ISSUE THREAD

**Issue by scholtzm** [tststs/atom-ternjs#158]
After updating to Atom 1.2.1 (or possibly 1.2.0), tern started crashing very often with the following error message:

> tern exited with code: null.

Anyone else having the same issue?

**Comment by flootr** [comment]
This affects me too, regularly. I am on 1.2.2 and atom-ternjs is 0.8.4.

**Comment by Stijnkool** [comment]
+1
Atom: 1.2.2
atom-ternjs: 0.8.4

**Comment by williamboman** [comment]
Happens all the time to me too, to the point where I don't bother to restart it.

FWIW, it _feels_ like this started happening when I started writing `.jsx`.

**Comment by tststs** [comment]
Since we find out what is happening, the server is restarting automatically.
Please update to 0.8.6.

**Comment by tststs** [comment]
atom/atom#9663

**Comment by scholtzm** [comment]
I haven't seen the error since I updated to 0.8.6.

**Comment by williamboman** [comment]
Doesn't seem to restart itself correctly. My console is filled with these errors too (not sure if they are ternjs related or not though);

![screenshot 2015-11-21 at 23 33 47](https://cloud.githubusercontent.com/assets/6705160/11320859/81686c52-90a8-11e5-86d0-4e0aad1ee0ae.png)

On `atom-ternjs@0.8.6`.

**Comment by tststs** [comment]
Does the error still occur?

**Comment by scholtzm** [comment]
I haven't seen the error for quite some time now. :+1:

**Comment by Stijnkool** [comment]
Same here. haven't seen the error for a while.

**Comment by tststs** [comment]
Seems to be fixed.
