### ISSUE TITLE
No completion, fetch api error

### ISSUE THREAD

**Issue by metal3d** [tststs/atom-ternjs#163]
Hi,

Using 0.9.1 

No completion, then I open developper console:

```
Fetch API cannot load http://localhost:45855/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'file://' is therefore not allowed access.
Uncaught (in promise) TypeError: Failed to fetch
  at TypeError (native)
```

I'm behind a proxy - I say it in case of you already have this kind of problem.

**Comment by sigxcpu76** [comment]
Had the same issue with Atom 1.1.x. Fixed by upgrading to 1.2.x.

**Comment by metal3d** [comment]
Thanks, I will check tomorow and close issue if it works.

**Comment by metal3d** [comment]
Works now, sorry for this issue. Upgrading atom fixed the problem.
