### ISSUE TITLE
Strange behavior when auto complete a path

### ISSUE THREAD

**Issue by AJIh** [tststs/atom-ternjs#164]
![chord](https://cloud.githubusercontent.com/assets/6063915/11401676/b5bea772-93ce-11e5-91f6-46c4e6a6017d.gif)
Hi. When I enter a path and stroke 'tab', the path name is auto completed with more characters (including quotes) than what I need. Is this a bug?

**Comment by tststs** [comment]
Yeah. It's pretty strange that the paths are recognized as a variable.
Couldn't reproduce the issue. If it's possible, please provide a demo project, so i can reproduce and fix the issue.

Greetings
