### ISSUE TITLE
Libs as origins

### ISSUE THREAD

**Issue by MayhemYDG** [tststs/atom-ternjs#17]
I have `ecma5` in `.tern-project`'s `libs`.
`Math.a` will suggest me `abs`, the documentation will give me a link to `ecma5`, clicking that link leads to an empty file.
Maybe it shouldn't link to anything?

**Comment by tststs** [comment]
I'm currently do not check if the returned origin is a file in the project or not.
Will definitely be fixed in the next releases.

Thx for reporting!
