### ISSUE TITLE
Disable "Find definition" mouse keybinding

### ISSUE THREAD

**Issue by Klathmon** [tststs/atom-ternjs#170]
The "Find Definition" (CTRL+Click) is interfering with root functionality.

I use CTRL+DoubleClick to multi-select multiple words to change them all at once with the multi-cursor system. The CTRL+Click from this plugin interferes and breaks that functionality. 

Is there a way to disable just this part, or if not then disable all keybindings in this package?

**Comment by tststs** [comment]
For a quick fix you can goto ```.atom/packages/atom-ternjs/lib/atom-ternjs-manager.js```.
Uncomment line 348 ```this.client.definition();```, then restart atom.

As this breaks core functionality on windows, what alternative key should be used?

Greetings

**Comment by Klathmon** [comment]
I appreciate the quick fix!

As for what works on windows, i think your best bet will be to allow it to be configurable (as annoying as that is).

The fact that there are over 50,000 installs and it looks like i'm the first person to really have this issues means it's obviously not breaking it for many people.

**Comment by tststs** [comment]
Yep, strange. But it breaks core functionality and needs to be fixed.
I am also a heavy user of the multi-cursor system, so this sucks.

I will try to fix this as soon as possible.

Thanks for the report.

**Comment by tststs** [comment]
So i checked it on a windows machine. ```alt-click``` seems to be fine with core functionality.
If i am wrong, please reopen the issue.

**Comment by vjpr** [comment]
I use `alt-click` for multiple cursors (as IntelliJ uses). This needs to be a config option.
