### ISSUE TITLE
"Back from definition" doesn't work in Ubuntu

### ISSUE THREAD

**Issue by DrakeLeung** [tststs/atom-ternjs#171]
When I use the `Ctrl-Alt-d` for a function's definition, then I wanna back, but the `Ctrl-Alt-Z`doesn't work

Ubuntu `14.04`, atom-ternjs `0.10.1`

`.tern-project File`:
```javascript
  "ecmaVersion": 6,
  "libs": [
    "browser",
    "jquery"
  ],

  "loadEagerly": [
    "/"
  ],
  "dontLoad": [
  ],

  "plugins": {
    "complete_strings": {},
    "node": {},
    "modules": {},
    "es_modules": {},
    "doc_comment": {
      "fullDocs": true
    }
  }
}
```

**Comment by tststs** [comment]
As i have no access to a Ubuntu system at the moment, could you provide some more information?
Are there any errors in the console or thrown by the package?

Greetings

**Comment by DrakeLeung** [comment]
I don't notice any  errors  in the console :( 
BTW, the *Completion* feature with `Ctrl-Space` doesn't work as well.

Thanks

**Comment by tststs** [comment]
Seems to be a general problem with keybindings. `ctrl-space` is a keybinding defined by `autocomplete-plus` the other is defined by `atom-ternjs`.

I will try to get ubuntu working with VirtualBox and will test it.
