### ISSUE TITLE
Node plugin not working as expected with JSON type definition file

### ISSUE THREAD

**Issue by slavj** [tststs/atom-ternjs#180]
I found this PR for tern (https://github.com/ternjs/tern/pull/551) which shows how to use JSON type definition files with node modules. 
Tested it with sublime's and vim's plugin by using the demo repo for PR (here: https://github.com/bennidhamma/tern-test-node-plugin) and it works as expected (images below).
![autocomplete-sublime](https://cloud.githubusercontent.com/assets/1261822/11690260/1e3dacea-9e96-11e5-85a7-0a400002c70a.png)
![autocomplete-vim](https://cloud.githubusercontent.com/assets/1261822/11714172/89d50f78-9f38-11e5-8b6a-525e21bd0a7f.png)

However, when using atom with atom-ternjs there is no autocompletion. Essentially same behaviour as tern before the PR - it works only if require statement is removed from the .js file (picture for failed autocompletion below).
![autocomplete-atom](https://cloud.githubusercontent.com/assets/1261822/11690341/701165d4-9e96-11e5-855b-d73ffd57b7eb.png)

.tern-project file from the PR repo:
```javascript
{
  "libs": [
    "browser",
    "jquery",
    "ScoutData"
  ],
  "plugins": {
    "node": {
      "modules": {
        "ScoutData": "=ScoutData"
      }
    }
  }
}
```
Is there perhaps some additional configuration needed in order for atom-ternjs to allow both a require statement and a JSON type definition file for autocompletion?

Edit: Updated the comment with the correct image for vim's autocomplete.

**Comment by tststs** [comment]
Works as expected with the latest version of `atom-ternjs`.

![bildschirmfoto 2015-12-11 um 14 23 26](https://cloud.githubusercontent.com/assets/3591665/11744707/df6879fe-a012-11e5-9498-34ee18722e76.png)

**Comment by tststs** [comment]
Are there any error in the console?

Maybe:

- restart, re-install the package.
- be sure tern isn't installes via npm install -g

**Comment by slavj** [comment]
Hi and thanks for a response.

Here is more information (some of it is new - after 0.11.0 update):

* Tern is not a global package. Below is a list of all such packages on this box:
![global-packages](https://cloud.githubusercontent.com/assets/1261822/11745688/41cc9e84-a01a-11e5-8a27-0c8104bf2cc5.png)

* Console prior to 0.11.0 update never showed any error. I'm not much of a coffee-script dev (this was a first time I looked at it to be honest :blush:) but from what I did manage to debug while testing it was a simple case of having an empty array of completions. I wish I made a note/screenshot with that but since it looked so much like the PR mention in first comment I figured it was down to plugin interop with tern and went on.

* After recent update to 0.11.0 even the autocomletion for a source file without require statement stopped working. This time however there is a console error. Below is a screenshot after restarting the atom-tern server and trying autocomplete for "ScoutData." on file without a require. 
![console-error](https://cloud.githubusercontent.com/assets/1261822/11745880/4baabb42-a01b-11e5-9473-c9bdf1636aa3.png)
One possibly good thing is that now both files (with and without a 'require') throw the same error on autocomplete.

* After updating to 0.11.0 and getting the above error, I went a step further and not only re-installed the package but also Atom itself (not a big deal since I use Webstorm and currently I'm only testing Atom to see if I can get a comparable dev environment).
First I uninstalled atom by following the steps noted in this topic: https://discuss.atom.io/t/how-to-completely-uninstall-atom-for-mac/9084/14
Then I installed the atom-tern package. So essentially its now a clean Atom with tern-atom package (picture below).
![atom-packages](https://cloud.githubusercontent.com/assets/1261822/11746239/5d9b6462-a01d-11e5-9d20-531d762ac36f.png)

Do you have any more tips on what to do in order to make this work?
Like I said, Atom is still something I'm just looking into so this issue is not that big of a deal for me. However, I'l probably have some free time later on to look into this more if you can point me in the right direction. Just keep in mind that coffee-script is not my forte :smile:

**Comment by tststs** [comment]
Could you please click the 404 message and copy the response text. Maybe there are some information behind that.
Which operation system you are using?

**Comment by slavj** [comment]
Sure, no problem.

I'm using OS X,  El Capitan (10.11.1).

As for the message, it's 400 (not 404) and the response text is: 
TypeError: Cannot read property 'text' of undefined

**Comment by tststs** [comment]
You are right. 400 :)
I am pretty clueless right now. All those undefined won't get us anywhere.
Seems to be a problem with Tern itself. Haven't seen anything like that until now.
From this perspective it could be anything right now. :crystal_ball: 

So. How to get more information...
We should try to to set the server to debug and hope there is some more information we can get.

If you find time, please navigate to `.atom/packages/atom-ternjs` open `libs/atom-ternjs-server.js` and set debug to true (line 43). Maybe verbose too, but i don't know if this is leading to anything.

Restart atom and try again.

Thanks and Greetings.

**Comment by slavj** [comment]
Since this sounds like it might take a while to find a cause I'l put this on my list of things to play with during the next round of spare time.
When that happens I'l try to look around the code in more details to avoid wasting your time. At last an excuse to look at coffee-script :)
Don't know when that will be but I'l update this thread when I find anything new (if you dont mind leaving it open).

Thanks again for checking this out and all the best to you.

**Comment by tststs** [comment]
Sure thing. Keep me updated. I will have a closer look later, maybe i find something.

**Comment by slavj** [comment]
I've finally been able to take another look at Atom and revisit this issue.
Good news: autocompletion now works as expected for an example with 'require'.
I see that there were a couple of updates for this plugin in the meantime so it must be that one of them has covered this issue. I'm not sure what could have been the root cause but I suppose it doesn't matter now.
Thanks again for your help with this issue and for continuing to work on the plugin.
