### ISSUE TITLE
require module insertions bug

### ISSUE THREAD

**Issue by Segflow** [tststs/atom-ternjs#192]
When typing 
```var http = require("http[TAB]```
it expands to 
```var http = require('""http")```
(Notice the extra ")

**Comment by srolija** [comment]
Hi, I'm experiencing same issue when entering file paths (eg. "../apis") or local modules (from .node_modules, eg. "sequelize") .
In both cases it inserts quotes along with selected string so it ends up having two quotes on both begining and end.
