### ISSUE TITLE
 v0.13.0 : Cannot read property 'knownModules' of undefined

### ISSUE THREAD

**Issue by AlexanderOMara** [tststs/atom-ternjs#201]
In the latest update, no auto-complete suggestions are coming up, and the following errors are appearing in the console.

> .atom/packages/atom-ternjs/node_modules/tern/plugin/node.js:15 Uncaught TypeError: Cannot read property 'knownModules' of undefined
> (3) atom-ternjs-server-worker.js:34 Uncaught TypeError: Cannot read property 'request' of undefined

`.tern-project`
```json
{
	"libs": [
	],
	"loadEagerly": [
	],
	"dontLoad": [
	],
	"plugins": {
		"node": {},
		"complete_strings": {},
		"doc_comment": {
			"fullDocs": true
		}
	}
}
```

`sample.js`
```js
'use strict';

module.exports.text = function() {

};
```

I'm having this issue on OS X. Other issue for reference: https://github.com/tststs/atom-ternjs/issues/193#issuecomment-172976950

**Comment by tststs** [comment]
Think i spotted the issue.
Testing right now.

**Comment by tststs** [comment]
Please test 0.12.1 and restart all instances.
If the issue still exists after updating feel free to re-open the issue.

Greetings.
