### ISSUE TITLE
Can't configure project

### ISSUE THREAD

**Issue by deathgaze** [tststs/atom-ternjs#217]
Every time I try to configure a project, I get this error.

This is when I obviously have a project open and focused on a JS file in it. 
![screen shot 2016-03-24 at 12 57 09 pm](https://cloud.githubusercontent.com/assets/1457993/14026276/15ad0f9e-f1c0-11e5-88fa-303f1f96bb65.png)

**Comment by nonameolsson** [comment]
Sometimes I also get this..

**Comment by vjancik** [comment]
Same issue. Can't configure.

**Comment by tststs** [comment]
is this still an issue?
