### ISSUE TITLE
"alt-o" does not show documentation - Win 7 64bit

### ISSUE THREAD

**Issue by DoubleElite** [tststs/atom-ternjs#218]
It's strange as the documentation shows on the auto-complete popup but I can't get it to show when hovering over a method and use the hotkey "alt-o" which is what the docs say to use.

Any thoughts? Can I manually configure a new hotkey?

**Comment by PhiLhoSoft** [comment]
Despite what the doc says, I found no key binding defined at all for Tern.
Actually, some of these described conflict with some built in Atom.
At least for Windows and Atom 1.7.
That said, given the opportunity of conflicts with Atom or other packages, it is safer to define no key bindings and let the user to define them.
Currently, mine are:

    'ctrl-shift-r': 'tern:references'
    'alt-shift-r': 'tern:rename'
    'ctrl-alt-z': 'tern:marker-checkpoint-back' # Mmmm, doesn't work
    'ctrl-alt-d': 'tern:definition'
    'alt-o': 'tern:documentation'

Note that ctrl-alt-z doesn't work. Tried with `tern:MarkerChecpointBack` and `tern:marker-check-point-back` too...
Note also that you have to click on the method name before hitting `Alt-o`, it doesn't work on hover.

**Comment by tststs** [comment]
as of 0.14 you can disable all keybindings via the package settings and define your own in your keymap. As @PhiLhoSoft stated, hover won't work.
