### ISSUE TITLE
Extra `div` element appears at bottom of Atom window

### ISSUE THREAD

**Issue by akivajgordon** [tststs/atom-ternjs#219]
There's a `div` element that is taking up some of my vertical window real estate, highlighted in green in the attached image. If it's actually supposed to be there, then what is its purpose?

Reproduction steps:

1. `$ atom foo.js`
2. Type any character in that .js file

Now, a 10px element appears at the bottom of my Atom window. The styles (also shown in the image) indicate a top/bottom padding of 5px, hence the 10px height.

If you can't reproduce it, I can try disabling other packages to see if one of them is causing the conflict. 

Using atom-ternjs v0.13.2 in Atom v1.6.2.

![atom-ternjs-type](https://cloud.githubusercontent.com/assets/6025036/14230115/d8700338-f918-11e5-9c06-1929a8db04ec.png)

**Comment by yianL** [comment]
+1
