### ISSUE TITLE
Version 0.14.x breaks atom autocomplete & snippets

### ISSUE THREAD

**Issue by MattDiMu** [tststs/atom-ternjs#226]
Updating atom-ternjs to 0.14.1 (from 0.13.2) disabled ALL autocompletion, even my custom snippets for all JavaScrip files. To be sure that atom-ternjs causes the problem, I disabled all other potential conflicting plugins. Uninstalling atom-ternjs and reinstalling version 0.13.2 fixed it for me.

I'm using:
Win7 (files have CRLF line endings)
atom@1.7.2
custom snippets from snippets.cson
the "normal" JavaScript autocomplete-plus (variables, some popular snippets like "for"-loops)

**Comment by fthebaud** [comment]
Commands to temporarily go back to 0.13.2: 
```
$ apm uninstall atom-ternjs
$ apm install atom-ternjs@0.13.2
```

**Comment by tststs** [comment]
- So are there any issues shown in the console?
- does it just breaks for a specific project? (sample code pls)

**Comment by fthebaud** [comment]
I believe this is a duplicate of #225

**Comment by tststs** [comment]
duplicate of #230
