### ISSUE TITLE
no autocomplete suggestion 

### ISSUE THREAD

**Issue by cuitl** [tststs/atom-ternjs#230]
when i enable the ternjs,the snippets disappeared

**Comment by tststs** [comment]
Could you please be a bit more specific?

- Which snippets?
- Does autocomplete does not work at all?
- What packages are installed and which snippets are not displayed?

**Comment by dandevs** [comment]
I also have this problem. Autocomplete seems to work fine if the file is in the projects root directory, but no where else.

**Comment by Icemic** [comment]
me too, and i find some errors in console

![image](https://cloud.githubusercontent.com/assets/837432/15096039/c775ef12-1519-11e6-89f3-20c6ae884fec.png)

they were outputing when i was inputing.

When i disabled ternjs, snippets appears again

**Comment by Robula** [comment]
Same issue here.
Windows 10 10576.240
Atom 1.8.0-beta3
atom-ternjs@0.14.1

**Comment by RallionRl** [comment]
I'm having the same issue, with Atom 1.7.3, atom-ternjs 0.14.1, and Windows 10 10586.318.

Also, it happens only in subdirectories. Given the same file, if it's at the root of the project, then completion works, without errors in the console, but if it's in any subdirectories, it doesn't work anymore and I have the same errors as @Icemic.

**Comment by SamuelColacchia** [comment]
Same issue as above.

atom-ternjs : does not work on js files in sub-directory of the project.

Workaround : add your js folders as projects then configure each folder. MUST KEEP THEM LOADED.

atom v : 1.7.3
atom-ternjs : 0.14.1

**Comment by vazh** [comment]
same issue here,

Atom 1.7.3
Windows 10
atom-ternjs 0.14.1

snippets, js autocomplete is gone too.
autocomplete & snippets in html works fine.

if i disable atom-ternjs, everything works again.

**Comment by Mascot1** [comment]
I also meet this question.Hope it will fix soon

**Comment by TopGrd** [comment]
Same issue here.  
Atom 1.7.0  
atom-ternjs@0.14.1

**Comment by lzgrzebski** [comment]
same here :(

atom 1.7.2
atom-ternjs@0.14.1

**Comment by Egorvoz** [comment]
Same here atom + windows 10. Linux works great.

**Comment by cuitl** [comment]
it perhaps me find this issue,but now I realize that i am stupid, please get into the atom-ternjs setting and select the 
"Use autocomplete-snippets" then restart the atom ,and aslo "they appeared" .... vv ,^^
----- 原始邮件 -----
发件人：Egor Voziyanov <notifications@github.com>
收件人：tststs/atom-ternjs <atom-ternjs@noreply.github.com>
抄送人：cuitl <spacesky214@sina.com>,  Author <author@noreply.github.com>
主题：Re: [tststs/atom-ternjs] no autocomplete suggestion  (#230)
日期：2016年05月26日 21点02分

Same here atom + windows 10. Linux works great.

&mdash;

**Comment by vazh** [comment]
@cuitl nope, still not working for me, as #233 wrote.
it doesnt work other than root path, since tern config file is there.

**Comment by jonathandelgado** [comment]
I know this isn't by any means a permanent solution, but downgrading fixed this for me.

```
apm rm atom-ternjs
apm install atom-terns@0.13.2
```

Don't forget to restart Atom.

**Comment by vazh** [comment]
yeah, downgrade atom-ternjs fixed it.

**Comment by rwatts3** [comment]
Any update on the fix for this? Although downgrading solved the issue temporarily it'd be nice to take advantage of the features in 0.14 +

**Comment by tststs** [comment]
0.14.2 should fix the issue.
Everything is working as expected on my Windows 10 via virtual box.

The error may still occur the first time autocompletion is triggered in each file.
This is due to the file isn't registered at first call to the server - haven't had time to fix this issue yet.
In most cases just save the file and trigger autocomplete again.

There is no guarantee 0.14.2 fixes the issue so please report if the issue still occurs.

**Comment by Klathmon** [comment]
@tststs It fixed the issue for me right away.

Atom 1.9.0-beta0, Windows 10 (Version 10.0.10586 Build 10586)

Thanks.
