### ISSUE TITLE
This plugin actually disabled the autocomplete function in the file that is not in the root path.

### ISSUE THREAD

**Issue by huiboliu** [tststs/atom-ternjs#233]
This plugin actually disabled the autocomplete feature in the file that is not in the root path.
When i disable this plugin, the autocomplete feature can then work fine. This is wired and unconvinient.

**Comment by Andrey-Zhiryakov** [comment]
I have this trouble to on winodws 10 with lastest atom version.

**Comment by belchevgb** [comment]
I have the same problem using Windows 10 and Atom latest version. Hope to fix it soon!

**Comment by shachar-i** [comment]
Got this issue as well

**Comment by WangQianliang** [comment]
same issue

**Comment by tststs** [comment]
duplicate of #230
