### ISSUE TITLE
How can I add complete folder and not just one js file?

### ISSUE THREAD

**Issue by RYG81** [tststs/atom-ternjs#237]
Hi,
Is it possible to add a project folder in ternJS loadEagerly section?

I have issue with ternjs as it not autocomplete my current working file functions. Can you suggest something?
Rahul

**Comment by tststs** [comment]
as mentioned in the readme:

```
"loadEagerly": [
    "path/to/your/js/**/*.js"
 ]
```

this will include all .js files located in path/to/your/js/ and subfolders
