### ISSUE TITLE
Failed to find library issue

### ISSUE THREAD

**Issue by RC-Chandan** [tststs/atom-ternjs#250]
After updating to **v0.15.0**, when I tried to restart the ternjs server its giving this error.

![screen shot 2016-08-27 at 2 00 01 am](https://cloud.githubusercontent.com/assets/10782742/18019586/71dc5aa4-6bfa-11e6-8ee1-7e78afe54402.png)

**Comment by LeonBlade** [comment]
Also experiencing the same problem, didn't think updating was going to kill my workflow.

**Comment by tststs** [comment]
there is no ecma5, ecma6 lib anymore. 
please update your .tern-project file.

**Comment by MethodGrab** [comment]
Are `.tern-project` files required to use atom-ternjs? I've never created one in a project and till I upgraded to v0.15.0 anything was fine, since updating I get both failed to find library errors.

**Comment by LeonBlade** [comment]
That was actually my situation, I didn't even have ecma6 or ecma5 listed in the `.tern-project` at all.  I just haven't upgraded still and so I haven't gotten around to doing any more testing with it.

**Comment by MethodGrab** [comment]
I've figured it out, I had a `.tern-project` file in my home dir. Deleting `ecma5` and `ecma6` from `~/.tern-project` fixed the errors!
