### ISSUE TITLE
Failed to find plugin lint

### ISSUE THREAD

**Issue by hoanghiep** [tststs/atom-ternjs#251]
After i update to 0.15.0, an error occurs when i start atom: "Failed to find plugin lint"
![untitled](https://cloud.githubusercontent.com/assets/1551503/18153141/beb0c2fa-7025-11e6-98c6-04b7e687abba.png)

**Comment by tinchoz49** [comment]
Hi @hoanghiep ! there is an issue where this was reported and answered: [link](https://github.com/tststs/atom-ternjs/issues/248#issuecomment-243048192)

**Comment by hoanghiep** [comment]
@tinchoz49 oh, thank you so much.
