### ISSUE TITLE
Tern snippets overlap custom snippets

### ISSUE THREAD

**Issue by sebfindling** [tststs/atom-ternjs#262]
Hello. This is something i've been struggling for a while. Everyime I want to use a custom snippet (for example "cl" for "console.log") I get Tern snippets first (in this case, "class"), so I have to move down until I select my custom one.

There should be a way to completely disable Tern snippets or a least move them below custom snippets.

**Comment by tststs** [comment]
This should do the trick.
Be sure to activate the `Display above snippets` option for the `atom-ternjs` package, this will display your custom snippets above all suggestions provided by Tern.

**Comment by tststs** [comment]
I'll properly prepare a release by tomorrow.

Greetings

**Comment by sebfindling** [comment]
@tststs thank you ver, very much; i forgot to get back to this discussion but i'm so happy about it <3
