### ISSUE TITLE
Integration with Hyperclick

### ISSUE THREAD

**Issue by rfreitas** [tststs/atom-ternjs#263]
With such an in depth JS analysis engine, it would make sense to have a better UX in terms of jumping to definitions of symbols, integrating with hyperclick would give that.
`js-hyperclick` already does a pretty good job, but it seems that a project like `atom-ternjs` could be better leveraged for this type of feature.

**Comment by tststs** [comment]
hyperclick support added by @smitt04 (0.17.0)
