### ISSUE TITLE
Deprecated selector in `atom-ternjs/styles/atom-ternjs.less`

### ISSUE THREAD

**Issue by Nikki1993** [tststs/atom-ternjs#265]
In `atom-ternjs/styles/atom-ternjs.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:
- `atom-text-editor .scroll-view .source.js .function:not(.meta):not(.type).atom-ternjs-hover,
  atom-text-editor::shadow .scroll-view .source.js .function:not(.meta):not(.type).atom-ternjs-hover,
  atom-text-editor .scroll-view .source.js .class .name.atom-ternjs-hover,
  atom-text-editor::shadow .scroll-view .source.js .class .name.atom-ternjs-hover,
  atom-text-editor .scroll-view .source.js .support.atom-ternjs-hover,
  atom-text-editor::shadow .scroll-view .source.js .support.atom-ternjs-hover,
  atom-text-editor .scroll-view .source.js .constant.other.atom-ternjs-hover,
  atom-text-editor::shadow .scroll-view .source.js .constant.other.atom-ternjs-hover,
  atom-text-editor .scroll-view .source.js .object:not(.delimiter).atom-ternjs-hover,
  atom-text-editor::shadow .scroll-view .source.js .object:not(.delimiter).atom-ternjs-hover,
  atom-text-editor .scroll-view .source.js .variable.atom-ternjs-hover,
  atom-text-editor::shadow .scroll-view .source.js .variable.atom-ternjs-hover` => `atom-text-editor .scroll-view .source.js .function:not(.meta):not(.type).atom-ternjs-hover,
  atom-text-editor .scroll-view .syntax--source.syntax--js .syntax--function:not(.meta):not(.type).atom-ternjs-hover,
  atom-text-editor .scroll-view .source.js .class .name.atom-ternjs-hover,
  atom-text-editor .scroll-view .syntax--source.syntax--js .syntax--class .syntax--name.atom-ternjs-hover,
  atom-text-editor .scroll-view .source.js .support.atom-ternjs-hover,
  atom-text-editor .scroll-view .syntax--source.syntax--js .syntax--support.atom-ternjs-hover,
  atom-text-editor .scroll-view .source.js .constant.other.atom-ternjs-hover,
  atom-text-editor .scroll-view .syntax--source.syntax--js .syntax--constant.syntax--other.atom-ternjs-hover,
  atom-text-editor .scroll-view .source.js .object:not(.delimiter).atom-ternjs-hover,
  atom-text-editor .scroll-view .syntax--source.syntax--js .syntax--object:not(.delimiter).atom-ternjs-hover,
  atom-text-editor .scroll-view .source.js .variable.atom-ternjs-hover,
  atom-text-editor .scroll-view .syntax--source.syntax--js .syntax--variable.atom-ternjs-hover`
- `atom-text-editor .scroll-view .atom-ternjs-definition-marker div,
  atom-text-editor::shadow .scroll-view .atom-ternjs-definition-marker div` => `atom-text-editor .scroll-view .atom-ternjs-definition-marker div,
  atom-text-editor .scroll-view .atom-ternjs-definition-marker div`
- `atom-text-editor .scroll-view .atom-ternjs-definition-marker.active div,
  atom-text-editor::shadow .scroll-view .atom-ternjs-definition-marker.active div` => `atom-text-editor .scroll-view .atom-ternjs-definition-marker.active div,
  atom-text-editor .scroll-view .atom-ternjs-definition-marker.active div`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by Aterocana** [comment]
Still have the problem here.
archlinux  4.8.13-1-ARCH
atom 1.13.0

**Comment by Nikki1993** [comment]
@Aterocana the issue has been fixed but afaik package hasn't been updated so wait for the new release.

**Comment by Aterocana** [comment]
@Nikki1993 Oh ok, thx.
