### ISSUE TITLE
ternjs for phaser support dosen't work after install other snippets

### ISSUE THREAD

**Issue by fenixwu** [tststs/atom-ternjs#267]
Hi, there. I'm a phaser and react developer.
There's a bug bother me a long time.

I install "atom-ternjs" and "tern-phaser".
To let atom support phaser snippet well.
I copy "tern-phaser" in node_modules to "~/.atom/package/atom-ternjs/node_modules/".

Phaser snippet act well, like this.
![Image of magic phaser](https://i.imgur.com/G0EqijN.png)

But it'll lose magic after I install react or any other snippet.
Like this.
![Image of no magic phaser](https://i.imgur.com/j5I5n6Y.png)

Seeking for any help, thank you.

---

I can't tell which site to report this issue.

Here or  tern-phaser?

So I raise issue both.

**Comment by tststs** [comment]
Could you post your config and versions (atom, atom-ternjs)?

I'll try to reproduce the issue if you send me a list of installed packages where tern-phaser works and a list and/or the package that breaks the autocompletion.

Greetings.

**Comment by fenixwu** [comment]
Hello, here's my atom setting

## Atom Ver.
1.12.2

## tern-phaser
0.2.0

## Atom package list (tern-phaser works)

Remote-FTP@0.9.4
activate-power-mode@1.1.0
advanced-open-file@0.16.4
atom-beautify@0.29.13
atom-jade@0.3.0
atom-json-color@0.4.2
__atom-ternjs@0.16.1__
auto-update-packages@1.0.1
dictionary@0.5.0
docblockr@0.8.7
duotone-dark-sea-syntax@2.0.0
editorconfig@2.0.5
emmet@2.4.3
file-icons@1.7.25
git-log@0.4.1
git-plus@5.25.1
git-time-machine@1.5.4
highlight-selected@0.11.2
hyperclick@0.0.39
js-hyperclick@1.9.0
language-markdown@0.18.1
linter@1.11.18
linter-eslint@8.0.0
linter-sass-lint@1.7.4
linter-shellcheck@1.4.1
merge-conflicts@1.4.4
minimap@4.25.6
minimap-git-diff@4.3.1
minimap-highlight-selected@4.4.0
minimap-linter@1.6.0
minimap-pigments@0.2.1
pane-layout-plus@0.7.3
pigments@0.37.0
project-manager@3.3.3
release-notes@0.53.0
sync-settings@0.7.2
synced-sidebar@0.4.3
uglify@1.2.6

## Error

I found that I can install "react@0.16.1", "react-redux-snippets@0.1.0" and tern-phaser work well.
Tern-phaser did not work after installing "language-javascript-jsx@0.3.7".

Since most react tools work well with tern-phaser right now.
I think it will be OK without "language-javascript-jsx".
