### ISSUE TITLE
The package is not working with latest version

### ISSUE THREAD

**Issue by jiayihu** [tststs/atom-ternjs#271]
I updated `atom-ternjs` with latest version and it's not working now. Suggestions are not displayed even if I have a `.tern-project` file in project root. Also I noticed that the command `Restart server` is disappeared from command palette.

Project configuration UI also is broken.
![schermata 2016-11-13 alle 13 11 56](https://cloud.githubusercontent.com/assets/10067273/20245506/65bd57a0-a9a3-11e6-85fb-d16ca58adfdb.png)

**Comment by brayanfernandes** [comment]
same problem for me

**Comment by jiayihu** [comment]
@brayanfernandes  I reverted to the previous version, which works great, for the time being:
```
apm install atom-ternjs@0.15.0
```

I think it's the cleanest solution while waiting for a fix (:

**Comment by tststs** [comment]
i thinck was the missing activation hook for the language-babel package.
Try again :)

**Comment by jiayihu** [comment]
@tststs Looks fine now :tada: Configuration UI is also fixed. Thanks for your great work!

**Comment by brayanfernandes** [comment]
thank you, now its working.
