### ISSUE TITLE
atom-text-editor.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by amitmtrn** [tststs/atom-ternjs#275]
The contents of `atom-text-editor` elements are no longer encapsulated
within a shadow DOM boundary. Please, stop using `shadowRoot` and access
the editor contents directly instead.
```
atom-text-editor.Object.defineProperty.get (/usr/share/atom-beta/resources/app.asar/src/text-editor-element.js:58:18)
<unknown> (/home/amit/.atom/packages/atom-ternjs/lib/atom-ternjs-manager.js:367:24)
Workspace.observeTextEditors (/usr/share/atom-beta/resources/app.asar/src/workspace.js:329:9)
Manager.registerEvents (/home/amit/.atom/packages/atom-ternjs/lib/atom-ternjs-manager.js:328:44)
Manager.activate (/home/amit/.atom/packages/atom-ternjs/lib/atom-ternjs-manager.js:92:12)
Manager.startServer (/home/amit/.atom/packages/atom-ternjs/lib/atom-ternjs-manager.js:163:16)
```

**Comment by Toxblh** [comment]
update pls.
release atom 1.13

**Comment by hasansan07** [comment]
I have the same issue. I reconfigured the project but still have the deprecation warning. Atom version is 1.13.0 and TernJs version is 0.16.1

**Comment by yPangXie** [comment]
+1, version of atom is 1.13.0 and atom-ternjs version is 0.16.1

**Comment by dshm** [comment]
+1, version of atom is 1.13.0 and atom-ternjs version is 0.16.1

**Comment by Oblik-Design** [comment]
How can I fix this ?
