### ISSUE TITLE
Can any one help on this?

### ISSUE THREAD

**Issue by ckoo7** [tststs/atom-ternjs#286]
The contents of atom-text-editor elements are no longer encapsulated within a shadow DOM boundary. Please, stop using shadowRoot and access the editor contents directly instead.
Report Issue
atom-text-editor.Object.defineProperty.get - /usr/share/atom/resources/app.asar/src/text-editor-element.js:68:18
<unknown> - /home/chandra/.atom/packages/atom-ternjs/lib/atom-ternjs-manager.js:367:24
Workspace.observeTextEditors - /usr/share/atom/resources/app.asar/src/workspace.js:329:9
Manager.registerEvents - /home/chandra/.atom/packages/atom-ternjs/lib/atom-ternjs-manager.js:328:44
Manager.activate - /home/chandra/.atom/packages/atom-ternjs/lib/atom-ternjs-manager.js:92:12
Manager.startServer - /home/chandra/.atom/packages/atom-ternjs/lib/atom-ternjs-manager.js:163:16

**Comment by piaoyidage** [comment]
Me too, anyone can solve this problem?
MacOS  Atom 1.13.0

**Comment by tststs** [comment]
fixed by @Greenek and published with `0.17.0`
