### ISSUE TITLE
add element.insertAdjacentElement/Text

### ISSUE THREAD

**Issue by dagolinuxoid** [tststs/atom-ternjs#290]
atom-ternjs 0.17.0 supports autocompletion for `.insertAdjacentHTML()` method but does NOT recognize `.insertAdjacentElement()` and `.insertAdjacentText()` methods. Take it to consideration.

**Comment by tststs** [comment]
`atom-ternjs` is just a wrapper for [ternjs/tern](https://github.com/ternjs/tern).
It seems that the definitions for the mentioned methods are missing.

You may open a issue/pull request there.

Greetings.
