### ISSUE TITLE
Reading the config may crash plugin

### ISSUE THREAD

**Issue by stffndtz** [tststs/atom-ternjs#3]
I tried to include angular and that is what i get:

![bildschirmfoto 2015-01-25 um 21 01 26](https://cloud.githubusercontent.com/assets/819140/5893028/fa1153fe-a4d5-11e4-8218-e42bda1fb9e3.png)

It would be awesome to have 2 things:

1) inform user if json is malformed (i.e. if you simply copy/paste the provided example)

2) alert user if specified lib/plugin is unavailable

**Comment by tststs** [comment]
The user now gets notified via atom notifications. No more console! :rocket:
