### ISSUE TITLE
No hint in the HTML label script

### ISSUE THREAD

**Issue by chenshanlong** [tststs/atom-ternjs#302]
In the.Js file can be used normally。
But Updated the 0.18X version after the emergence of this problem，
And I like your code base

log:
internal/process/warning.js:24 (node:70099) Warning: Possible EventEmitter memory leak detected. 11 ipc-helpers-window-method-response listeners added. Use emitter.setMaxListeners() to increase limitprocess.on @ internal/process/warning.js:24
/Users/shanlong/.atom/packages/atom-ternjs/lib/atom-ternjs-server.js:152 child process disconnected.

**Comment by tststs** [comment]
the package currently does not support autocompletion in script tags (html, php) closing this in favor of enhancement issue https://github.com/tststs/atom-ternjs/issues/317
