### ISSUE TITLE
Accidental prototype loop crashes tern-server

### ISSUE THREAD

**Issue by TitanNano** [tststs/atom-ternjs#305]
This is not directly a bug in atom-ternjs or ternjs it self. It's rather an edge-case which should be properly handled.

When doing something like this
```JavaScript
const SomeObject = {
    property: "value",
    prop2: 123,
    method() {},

    __proto__: SomeObject
};
```
it is attempted to set the object as it's own prototype. 

This code wouldn't work, since the object isn't declared at the time it should be set as the prototype, but Tern already knows about it. This results in an infinite loop, which exceeded the stack and gets the tern-server killed. 
The server will continue to be killed until the code snipped is fixed. 

It would be great if this case could be handled appropriately, so the user is not left in the dark about what is causing the server to crash.

**Comment by tststs** [comment]
This should be fixed with updating the tern dependency. If the error still occurs after the next release feel free to re-open the issue.
thx
