### ISSUE TITLE
Better autocomplete support?

### ISSUE THREAD

**Issue by PixelT** [tststs/atom-ternjs#316]
For example, ternJS autocomplete in SublimeText:

![SublimeText](http://i.imgur.com/oHcASxS.png)

and in Atom:

![Atom](http://i.imgur.com/eIy07LR.png)

In Sublime I can write random letter and they will provide me all completions which have those letters (no matter about order), in atom I must provide it in this same order as function name

I think this functionality called **fuzzy search** ?

**Comment by jdavis-software** [comment]
@PixelT once you've install the `tern-js` package you need to restart the server.

![screen shot 2017-10-19 at 11 26 05 pm](https://user-images.githubusercontent.com/21320194/31807779-f591d0c6-b524-11e7-87e9-35f424a5c823.png)

Once you've restarted the server you autocomplete will work just fine. 

![screen shot 2017-10-19 at 11 27 19 pm](https://user-images.githubusercontent.com/21320194/31807811-1634273e-b525-11e7-8ae5-195af4dcbd31.png)

**Comment by tststs** [comment]
@PixelT 

to use `browser` features like `document` you need to activate the required lib `browser`. This is done in `Packages -> Atom Ternjs -> Configure Project.

![screenshot 2019-03-03 at 18 58 07](https://user-images.githubusercontent.com/3591665/53699240-82ef3d00-3de6-11e9-8baa-3693991d528f.png)

After that hit the bottom CTA `Save & Restart Server`
