### ISSUE TITLE
Can't disable docs

### ISSUE THREAD

**Issue by mhnavarro** [tststs/atom-ternjs#318]
I want to disable the docs, because comments takes a lot of space on screen
and it blocks part of the code

I opened the ternjs config and deleted the docs related stuff using the GUI provided by this package,
but the docs keep showing. Already restarted the ternjs server and atom. No luck.

Config file
```
{
  "ecmaVersion": 6,
  "libs": [
    "chai"
  ],
  "loadEagerly": [],
  "dontLoad": [
    "node_module/**"
  ],
  "plugins": {
    "node_resolve": {},
    "es_modules": {},
    "requirejs": {
      "baseURL": "",
      "paths": "",
      "override": ""
    },
    "commonjs": {}
  }
}
```

**Comment by jssuttles** [comment]
Perhaps a toggle in Packages -> Atom Ternjs?

Toggle documentation

**Comment by mhnavarro** [comment]
Yeah!!, thanks
