### ISSUE TITLE
TypeError: Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by hexus** [tststs/atom-ternjs#324]
I see this error quite often when working with the Phaser framework. All I have is a couple of libraries eager-loaded.

It tends to hang the entire editor for a few seconds before this error occurs (nothing is shown in the Atom GUI, just this in the console).

Here's a screenshot from Atom's dev tools:

![image](https://user-images.githubusercontent.com/2626789/28438363-c9cc571c-6d95-11e7-8891-19dfeba1bdde.png)

**Comment by tststs** [comment]
This might be an issue with tern itself. Please provide sample code where the error occurs and i'll try to fix it.

**Comment by hexus** [comment]
I'm no longer using Atom or Tern. I posted this nearly two years ago. :slightly_smiling_face:

**Comment by tststs** [comment]
:)
