### ISSUE TITLE
Imported functions signatures.

### ISSUE THREAD

**Issue by Astrydax** [tststs/atom-ternjs#332]
I'm refactoring my code and extracting functions away from main.js into their own files .  The main reason I'm using this package is to see the function signatures, specifically the param list (I always forget order of parameters). It would be nice when calling functions required in from a different .js file, to be able see at a glance which params I need to pass, and in which order.

**Comment by tststs** [comment]
This works if the package is configured correctly. Also see this issue: https://github.com/tststs/atom-ternjs/issues/346

If the issue persists, please post an example repo to reproduce the issue and your .tern-project config.

thx
