### ISSUE TITLE
Tern js no longer does any autocomplete

### ISSUE THREAD

**Issue by pingshunhuangalex** [tststs/atom-ternjs#341]
Probably since the update to Atom 1.25. ternjs seems to stop working. It starts with console command like console.log not autocompleted. Now nothing gets suggested in js file. No idea what happened...

**Comment by ryancole** [comment]
Still appears to be happening for me, too.

```
PS C:\Users\rcole\Documents\Visual Studio 2017\Projects\portal-web> apm ls --installed
Community Packages (9) C:\Users\rcole\.atom\packages
├── atom-ternjs@0.18.3
├── busy-signal@1.4.3
├── file-icons@2.1.17
├── intentions@1.1.5
├── language-babel@2.84.0
├── linter@2.2.0
├── linter-eslint@8.4.1
├── linter-ui-default@1.7.1
└── prettier-atom@0.52.0
```

**Comment by adityavm** [comment]
@pingshunhuangalex can you confirm if after you type in something, then wait a while (for me it's ~17s), the autocompleter ultimately does show up?
