### ISSUE TITLE
Autocomplete doesn't work cross files

### ISSUE THREAD

**Issue by JestDotty** [tststs/atom-ternjs#346]
atom-ternjs v0.18.3

I've restarted the server between changes

`.tern-project`:
```json
{
	"ecmaVersion": 6,
	"libs": [],
	"loadEagerly": [
		"exportTest.js"
	]
}

```

`exportTest.js`:
```js
module.exports = class Extensible{
	methodA(){
		
	}
}
```

`test.js` lacking autocomplete:
![image](https://user-images.githubusercontent.com/4729968/39934558-36fa7902-5514-11e8-8f08-31f81bab3af3.png)

---

`test.js` with Extensible definition within the file does autocomplete:
![image](https://user-images.githubusercontent.com/4729968/39934634-7025ce7a-5514-11e8-9d8e-6b5e353dd592.png)

---

(something else weird is while with a local definition a `.` is sufficient enough to show the properties available, with the require it just gives me random stuff:
![image](https://user-images.githubusercontent.com/4729968/39934811-095fdf72-5515-11e8-9f2f-63b323a9ae9b.png)
)

**Comment by tststs** [comment]
In the first example you use require. This means the plugin needs to be configured accordingly.

1: Packages -> Atom Ternjs -> Configure project
![screenshot 2019-03-03 at 16 54 38](https://user-images.githubusercontent.com/3591665/53697830-becdd680-3dd5-11e9-8af2-d0759780ed3f.png)

2:
![screenshot 2019-03-03 at 16 53 31](https://user-images.githubusercontent.com/3591665/53697838-e15fef80-3dd5-11e9-8d27-eefaa430c168.png)

3: Example repo you can test the above results
https://github.com/tststs/atom-ternjs-using-requirejs

Greetings!
