### ISSUE TITLE
100% CPU usage after file close

### ISSUE THREAD

**Issue by qwelias** [tststs/atom-ternjs#352]
Recently [js-hyperclick](https://atom.io/packages/js-hyperclick) package began to require [hyperclick](https://atom.io/packages/hyperclick) to be installed.

I'm not who to blame but if hyperclick is enabled then `atom-ternjs-server-worker.js`'s CPU utilization goes to 100%

I'd like to profile it, but am not sure how to specify exec flags to run it with `--inspect` so I can attach DevTools

**Comment by qwelias** [comment]
My initial assumption regarding hyperclick was incorrect.

Example `.tern-project`:
```
{
  "ecmaVersion": "7",
  "libs": [],
  "loadEagerly": [],
  "dontLoad": [],
  "plugins": {
    "doc_comment": true,
    "node": {
      "dontLoad": "",
      "load": "",
      "modules": ""
    },
    "node_resolve": {},
    "modules": {
      "dontLoad": "",
      "load": "",
      "modules": ""
    },
    "commonjs": {}
  }
}
```

Steps to reproduce:
1. open Atom
2. open any js file
3. require a lib and try to see it's autocompletions
4. close opened file
5. look at cpu load

After just a few seconds of profiling the worker you can see that `process._fatalException @internal/bootstrap/node.js:444` eats around 45% of process time because it gets bombarded with errors.
Error stack:
```
Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at process.target.send (internal/child_process.js:627:16)
    at process.<anonymous> (/home/qwelias/.atom/packages/atom-ternjs/lib/atom-ternjs-server-worker.js:119:11)
    at process.emit (events.js:182:13)
    at process._fatalException (internal/bootstrap/node.js:451:27)
```

**Comment by qwelias** [comment]
I'd suggest adding a `process.exit(1)` in `process.on('uncaughtException')@atom-ternjs-server-worker.js` in case `err.code` is `ERR_IPC_CHANNEL_CLOSED`, but I have no idea if worker is supposed to global or there's multiple per client js file.

**Comment by qwelias** [comment]
So what happens is on `disconnect` worker does `process.kill()` but does not specifies `pid` which is mandatory, then it just goes into infinite recursion

**Comment by dpisklov** [comment]
+1 here
