### ISSUE TITLE
CSP error during initialization

### ISSUE THREAD

**Issue by mattsawyer77** [tststs/atom-ternjs#36]
I saw this while debugging another package, upon reloading Atom:

>Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

Seems to come from elmer.

**Comment by tststs** [comment]
Yep, seems to be elmer. elmer hasn't been updated for like 4 month and i tried a custom element for the rename-view. Does this affect the package at it self or can we just ignore it for now?

**Comment by tststs** [comment]
Fixed by <a href="https://github.com/tststs/atom-ternjs/commit/1dd6a1fce7ab5c09c9a2119fbe4b426cc8b66d80">commit</a>
