### ISSUE TITLE
Discussing moving to autocomplete+ new provider API

### ISSUE THREAD

**Issue by despairblue** [tststs/atom-ternjs#4]
Hey, would you mind joining https://gitter.im/atom-community/autocomplete-plus to discuss integrating ac+'s new [provider api](https://github.com/atom-community/autocomplete-plus/wiki/Provider-API).

Btw: congrats for creating the first ternjs plugin for atom that actually worked for me :smiley:

**Comment by tststs** [comment]
Thx! I really appreciate it.
For sure i will have a look into the discussion and the new provider API. Looks pretty awesome!

I'm pretty busy right now, but there will definitely be a patch, using the new provider API as fast as possible.
