### ISSUE TITLE
Refused to eval string as Javascript because 'unsafe-eval'

### ISSUE THREAD

**Issue by ericcirone** [tststs/atom-ternjs#44]
Error on startup.

Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

Mac
Atom ver 1.816.0
Plugin ver 0.5.2

**Comment by mapaiva** [comment]
Same problem here. I have this message on startup Atom and ternjs do not work.

Any ideas?

**Comment by tststs** [comment]
The error is thrown by atom/elmer and shouldn't affect the package at all.
If the package isn't working for you, there must be another problem. Please open another issue (console, stack trace) with your problem.

thx
tststs

**Comment by mapaiva** [comment]
Thanks @tststs 

#47 Open.

**Comment by tststs** [comment]
Duplicate of #36

**Comment by tststs** [comment]
Fixed by <a href="https://github.com/tststs/atom-ternjs/commit/1dd6a1fce7ab5c09c9a2119fbe4b426cc8b66d80">commit</a>
