### ISSUE TITLE
Doesn't work behind http proxy

### ISSUE THREAD

**Issue by noseglid** [tststs/atom-ternjs#46]
```
Updating to “atom-ternjs@0.5.3” failed.Hide output…

npm ERR! git fetch -a origin (git://github.com/marijnh/tern.git) fatal: unable to connect to github.com:
npm ERR! git fetch -a origin (git://github.com/marijnh/tern.git) github.com[0: 192.30.252.129]: errno=Network is unreachable
npm ERR! Linux 3.13.0-46-generic
npm ERR! argv "/opt/atom/resources/app/apm/bin/node" "/opt/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/alexo/.atom/.apm/.apmrc" "--userconfig" "/home/alexo/.atom/.apmrc" "install" "/tmp/d-11529-17479-1g7v620/package.tgz" "--target=0.21.0" "--arch=x64"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code 128

npm ERR! Command failed: fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.129]: errno=Network is unreachable
npm ERR! 
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-11529-17479-1wy7siv/npm-debug.log
```

Yes, I have http proxy set for `apm`, `npm` and the environment where Atom is started. The problem is that the dependency on `tern` is a git url. If this was changed to the HTTP equivalent (supported by Github) `http://github.com/marijnh/tern.git` it would likely work.

**Comment by papodaca** [comment]
+1 Seeing this problem as well.
Adding the following to ~/.gitconfig should work around this issue. Does not seem to help in this case.
```
[url "https://"]
          insteadOf = git://
```

**Comment by tststs** [comment]
apm will always end with a 406 with http/https. There is no way of doing this atm.
I'll open a issue at apm.

thx
tststs

**Comment by noseglid** [comment]
I'm using several other repositories where switching git:// to https:// simply is not an option.

Why wouldn't simply altering the dependency to 'https' solve the issue?

**Comment by papodaca** [comment]
@noseglid 
The urls can be more specific:
```
[url "https://github.com"]
          insteadOf = git://github.com
```

**Comment by tststs** [comment]
The problem seems to be part of ```node 0.12.0```. See issue <a href="https://github.com/npm/npm/issues/7560">#7560</a> at npm.
As long this issue isn't fixed, i can't switch to https.

**Comment by booooh** [comment]
That issue has been closed, it seems that there wasn't a real issue with core node. I think the real problem is: https://github.com/atom/apm/issues/106
I believe that switching to git+https should work as a workaround in any case.

**Comment by lukeapage** [comment]
awesome I can upgrade now, thanks
