### ISSUE TITLE
Does not load terns included plugins

### ISSUE THREAD

**Issue by Cortys** [tststs/atom-ternjs#48]
Just a minor issue but the plugin does not load terns included node.js, require.js... plugins. The JSON definitions are working fine.

![screenshot 2015-03-10 23 44 13](https://cloud.githubusercontent.com/assets/1737630/6587024/57f68428-c77f-11e4-848e-550bbd3c6aa1.png)

**Comment by tststs** [comment]
Hey there,

you need to load node as a plugin not as a library:

```
{
  "libs": [
    "browser",
    "jquery"
  ],
  "loadEagerly": [
    "ternjs-test/**/*.js"
  ],
  "plugins": {
    "node": {},
    "angular": {},
    "complete_strings": {},
    "doc_comment": {
      "fullDocs": true
    }
  }
}
```
