### ISSUE TITLE
Prevent menu from popping on semi-colon or space

### ISSUE THREAD

**Issue by mattsexton** [tststs/atom-ternjs#53]
Is it possible to prevent tern from showing completions on entering a semi-colon or space? Its rather annoying because when I write a line and hit ';' to complete the line, the natural behavior is to hit enter to start the next line, but tern is showing completions and enter inserts a '$' (since jQuery is there, the $ shows first).

Good work though, thanks!

Edit:
After I submitted this, i noticed that it only happens after something like `functionCall();` not on something like `var x = 1;`

**Comment by yumitsu** [comment]
+1 on this, this is very annoying.

**Comment by tststs** [comment]
v0.5.10 includes a temporary fix for that problem.
Not perfect, but it will work for now.

The total prefix logic needs a overhaul :)
But i'm to busy right now.

**Comment by yumitsu** [comment]
@tststs Thanks!

**Comment by mattsexton** [comment]
Thanks for the fix!
