### ISSUE TITLE
ViewRegistry.addViewProvider is deprecated.

### ISSUE THREAD

**Issue by d4k0** [tststs/atom-ternjs#57]
Since the update to Atom 0.189.0, this message appears:

atom.views.addViewProvider now takes 2 arguments: a model constructor and a createView function. See docs for details.
```
ViewRegistry.addViewProvider (D:\Programme\Dokumente\Atom\resources\app\src\view-registry.js:33:14)
ViewManager.registerViewProvider (C:\Users\Daniel\.atom\packages\atom-ternjs\lib\atom-ternjs-view-manager.coffee:16:15)
```

**Comment by tststs** [comment]
Fixed by <a href="https://github.com/tststs/atom-ternjs/commit/1dd6a1fce7ab5c09c9a2119fbe4b426cc8b66d80">commit</a>
