### ISSUE TITLE
Tern server opened in wrong project folder

### ISSUE THREAD

**Issue by vramana** [tststs/atom-ternjs#61]
I had two project directories open in tree view. The second project has the `.tern-project` file and the js file I was working on. I was getting the no autocompletions from the plugins. I tried restarting the tern server but it had no effect.

So, I closed the first project directory and restarted the tern-server. Now I was able to see autocompletions from the plugins. 

I think the fix should be consider the path of file open in activeEditor if there is one while restarting the tern server. 

Sorry, for my bad english (non-native english speaker).

**Comment by tststs** [comment]
Hey,

Yes. Supporting multiply projects is on the todo list :)

Thx for reporting.
tststs

**Comment by vramana** [comment]
Thanks for the quick reply. On a side note, after I press writing tab to write another function parameter, the cursor doesn't leave a space after the comma. It is kind of annoying to insert it manually. 

And thanks for the plugin I waited this for so long. I just discovered this recently.
