### ISSUE TITLE
require'd class not auto-completed

### ISSUE THREAD

**Issue by Rukenshia** [tststs/atom-ternjs#64]
I can't get this to work properly. Maybe my documentation is just wrong?

All files are in the same directory.

foo.js

```
/**
 * @class Foo
 * @classdesc the very advanced Foo class
 */
function Foo () {
    this.bar = "yup";
}

/** Says hello */
Foo.prototype.sayHello = function () {
  console.log("hello.");
};

module.exports = Foo;
```

main.js

```
/** @type {Foo} */
var Foo = require('./foo');

new Foo().sayHello(); // This does not get auto completed when typing '.', just after typing two characters

// .sayHello also gets auto completed, no 'new Foo()' needed
```

.tern-project

```
{
  "libs": [
  ],
  "loadEagerly": [
    "*.js"
  ],
  "plugins": {
    "complete_strings": {},
    "node": {},
    "angular": {},
    "requirejs": {},
    "doc_comment": {
      "fullDocs": true
    }
  }
}
```

**Comment by tststs** [comment]
Does work for me. Or do i misunderstand the issue?

![bildschirmfoto 2015-05-03 um 22 20 25](https://cloud.githubusercontent.com/assets/3591665/7446744/ae7d222e-f1e2-11e4-9dc0-28de3a262df7.png)

greetings
tststs

**Comment by Rukenshia** [comment]
And exactly that does not work for me. I am on Windows 10 (Technical Preview, Build 10074), Atom 0.196.0, atom-ternjs 0.5.23.

**Comment by Rukenshia** [comment]
Just tested it on a Windows 8.1 VM, same issue.

**Comment by tststs** [comment]
Will evaluate this tomorrow. Too busy and no windows-machine... :)

**Comment by tststs** [comment]
Can't get atom + package to work or even install in my VM. Don't know why.
Tomorrow i may have the change to test on an Windows 7 machine. Does this issue occurs on Windows 7?
