### ISSUE TITLE
"Packages -> Atom Ternjs -> Create default .tern-project" has no effect

### ISSUE THREAD

**Issue by pesho** [tststs/atom-ternjs#69]
As the title says. When I choose this from the menu, no `.tern-project` file is created in the opened project. Package version is v0.5.24. I tried setting a breakpoint at the beginning of the `createTernProjectFile` function, but it's never triggered. I don't see anything interesting in the dev tools console either.

**Comment by tststs** [comment]
fixed with commit <a href="https://github.com/tststs/atom-ternjs/commit/26dfd107c8fe55654e76d706fe772dc18cd56735">26dfd10</a>
