### ISSUE TITLE
RangeError: Maximum call stack size exceeded at canonicalType

### ISSUE THREAD

**Issue by danvalang** [tststs/atom-ternjs#70]
Hello, just installed this, and i'm having trouble with this error, almost always pops out, reproduction: Just make a require or almost anything else and this pops out multiple times

RangeError: Maximum call stack size exceeded at canonicalType (/home/dvalle/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:274:58) at Object.extend.getType (/home/dvalle/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:131:14) at similarAVal (/home/dvalle/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:210:19) at /home/dvalle/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:237:50 at Array.every (native) at similarType (/home/dvalle/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:237:19) at similarAVal (/home/dvalle/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:212:12) at similarType (/home/dvalle/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:229:32) at exports.simplifyTypes (/home/dvalle/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:251:23) at Object.extend.toString (/home/dvalle/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:137:24)

**Comment by tststs** [comment]
Hey there. This package makes use of <a href="https://github.com/marijnh/tern">marijnh/tern</a>, you may post an issue there and provide some more information like a snippet to reproduce the issue. 
@marijnh

thx
tststs

**Comment by tststs** [comment]
Does this error still occur?
Feel free to reopen the ticket anytime.
