### ISSUE TITLE
Add tern-lint support

### ISSUE THREAD

**Issue by tststs** [tststs/atom-ternjs#72]
<a href="https://github.com/angelozerr/tern-lint">angelozerr/tern-lint</a>

- [x] use linter
- [x] add option to enable/disable tern-lint
- [ ] check if tern-lint is loaded as a plugin (server)

**Comment by angelozerr** [comment]
Thanks @tststs to integrate tern-lint inside atom.

When you have finished your integration. Could you create a PR please (with a screenshot) to mention your integration at https://github.com/angelozerr/tern-lint#integration

Thanks!

**Comment by tststs** [comment]
for sure! :)

**Comment by ericelliott** [comment]
How do I use tern-lint with Atom? Are there config instructions anywhere?
