### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by jhonasn** [tststs/atom-ternjs#76]
First very thanks for this amazing package that you created!

atom-ternjs is very beautiful, I really love the style but the performance is not so good as ternific (extension of brackets), so why ternific is more faster than atom-ternjs? is it by some different use of tern.js api like use [programming interface](http://ternjs.net/doc/manual.html#server_api) instead http server?

**Comment by tststs** [comment]
Maybe, maybe not.
Performance is definitely on the todo list and will be part based on the current minor release.
But first of all it is essential to spot the parts, were the performance issues occur.

You may help by analyzing some profiles you can easily create via the dev-tools.
Any help is welcome.

thx
tststs

**Comment by jhonasn** [comment]
Thanks for the response, when I can arrange some free time I'll try to help

**Comment by tststs** [comment]
Closing this in favor of #193
