### ISSUE TITLE
Failed to spawn command

### ISSUE THREAD

**Issue by slowdata** [tststs/atom-ternjs#92]
Every time i try to enable atom-ternjs i get this error:
Failed to spawn command
C:\Users\Username\.atom\packages\atom-ternjs\node_modules\.bin\tern. Make sure C:\Users\Username\.atom\packages\atom-ternjs\node_modules\.bin\tern is installed and on your PATH

I have Tern installed and in Path (running the command tern starts a server).

**Comment by tststs** [comment]
<a href="https://github.com/tststs/atom-ternjs/issues/91">https://github.com/tststs/atom-ternjs/issues/91</a>

**Comment by tststs** [comment]
duplicate of #90
