### ISSUE TITLE
Conflict with autocomplete-paths package

### ISSUE THREAD

**Issue by itadakimas** [tststs/atom-ternjs#94]
Hi there !

I noticed that atom-ternjs gets priority over autocomplete-paths. I guess that this issue is a duplicate of #18, but I'm not sure.

Is there something I can do ?

Anyway, this package is awesome ! Thanks !

**Comment by tststs** [comment]
Fixed with [a277739](https://github.com/tststs/atom-ternjs/commit/a2777396b5320ab6b1d0bcfbc2c3542d7045c7bf)
